apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      interval: 10m
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
        containers:
          main:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: 2.8.1
            env:
              AUDIOBOOKSHELF_UID: 568
              AUDIOBOOKSHELF_GID: 568
              CONFIG_PATH: /config
              METADATA_PATH: /config/metadata
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                memory: 4000Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 995 # abs
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 2Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config
    persistence:
          cache:
            type: emptyDir
            globalMounts:
              - path: /cache
          media:
            type: nfs
            server: cephalonas.lan.gigglesquid.tech
            path: /mnt/main/media/audiobookshelf
            globalMounts:
              - path: /media
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 80
    ingress:
      main:
        enabled: true
        annotations: 
          caddy.ingress.kubernetes.io/disable-ssl-redirect: "true"
          kubernetes.io/ingress.class: caddy
        hosts:
        - host: squidcasts.cephalonetes.lan.gigglesquid.tech
          paths:
          - path: /
            pathType: Prefix
            service:
              name: audiobookshelf
              port: *port
