# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &squid age1dwp8gxep67hf2mux2e54qqel6cs7ndvp008vsdv5t984s68reu0sxkm04q

  - &squid-rig age1qvktpvzde3rfnjnt3y9s9fvt9m23cgzqmp5qhgtrwgwqp70m7ewqnkkup4
  - &squid-top age1mfe5l2x5prlvdxzy9vnfau7grl8xyapnzud9qqk6hx9uagj0sppsjlt0v0

  - &caddy-dmz age1uuuqrhvn5kx4qd92xjv0qmj85ve2c53g85gypvzku77m67qm2pasflluqq
  - &caddy-internal age1k8wmvwravcdk5gsh2k6rhe003ardaup476nn8mafdmzrs30f6vasf2mgae

  - &timesquid-0 age1m6qkmvryf4fmmus2nrmrauphlsqtt6q8flzd2wyn30xgplvse9msk0tarv

  - &ns1 age1yd33u8d4hv7luchzfkfnfvmu83n2akezlslx8dcujftk0g0enyrqmwru0d
  - &ns2 age1t423w78ykm3c8yqe2jdw5t87pckev278tfvwgtshcetu2yve7e7sv5edv9

  - &mail age1vyvzys6ugu8hxzyetfnvtcjxf2emf8e37zk6tkmz7lllk2rm9fwsw8w2df

  - &i2p age1naucvcsg7p4hjp3fz0y0dh2c6c6ue5wph2paza26r8qzryl87dzq48r9ck

  - &crowdsec age1vpehquv0qyhm4ennfdwrry4afe5wwfckl8wnxecewfn97d7tlyvs6up04l
  - &otel age1nwqz2a2rgvaqcz7lmnjd5ryxyecv0h5h46lx88ma3gx2h4f28ahqe8rjrf

  - &torrent age1zswh4xxkyax7m527lx4slu45nfav57rs7frv2l3wuhhcvfm83yrqp27ezm
  - &squidjelly age14w9jvwngg85ph6e7yal3t5xmpg20s393vndgmznzl2vdfqgcsv0qy2huzn
  - &squidcasts age1tvesv74czg5uw9cce9gvzmda9xfdlk9g0ua6d37jkqyla6ayxv2sxfr5g4

  - &minesquid-velocity age1w2ehy9jxjktra2gfm4yz2ah92z3eedfjh9z4hd32293r2pzas5tst9995h
  - &minesquid age1r04g2t3ttcafjghfurvshqrtdepev2qt062lzvevk9txnzw2f4yswdunew

  - &unimatrix age1xp8y9snexane7duz53h8xx0vwxy8a6mhdh2rn5edrjuts5fegsgqxl7ecd

  - &umami age1ncaqyufadcyz5kwe443a0spjljcpvel02m5l80uwvchek03qs5sqwm2z9z

  - &uptime age1nakqr9jkwqxjgcnm6pamc2yjnj6rsjs7nlmgun6wh8xx5h0zl34symp40v

  - &squidsurvey age1zsm0ahwm4xh23k59ha2thzq3pjas50fyz9ghlykdde4re2u563js75melm

  - &gigglesquidtech age1735wpngc823k4trcp0ayzfnreqntvez8uymz048sv4wy59h0k9jq3r6pmj
  - &thatferretblog age1vghjsjt0rnqw8spwdgqesaqjs8kg725wkvvmhua94j3uaryg0c9snj6u67
  - &thatferretshop age16uf9ff3933s2uyxu74cgm34090k9pr8z4g0n33nlzrt76ha3wfcq0aayzp
  - &cfwrs age1as0xm26nvwdvxqyw6wg0je8zhwvjt8szqedzm88svwaw7uea6dds7q8n3z

  - &boinc-tentacle0 age13mk5pue6mlr3rjkrppxafcc2wz8wsygdhnt4jx335wxwaph5yads057hej

  - &searxng age1uzsyvn7arkk5xs6tagcn3leu2zn52equl3f66yhq2shdx3pzj3msgr77lx

  - &atuin age13mwtjzqadx0ylnft42j6qep96aktfkp9zndt2ekg6cjywzrske8qtcfh5j

  - &warrior-archiveteam age15dnpa7pl8u7660dpl5n8h69tdqx3jptv5wmrp337qn8qz7akcy8s4xrepd

  - &attic age16mrp5d9asz6fcwe26k6wgya7805ltg2q8r8lskdrjnkw0s2sv4cs6dcxgs
  - &ncps age1d4qfwa6aqdardzprjgqn66uet7nr2vcfg57z0uuameut9grrxessxngt8l

  - &vaultwarden age1pv8l33zaz2zteffj0expa4ax7gz9w67v93u33ufql5526luxggqswpjfj4

  - &netbox age17gg7eeagmcnepvdlatnuhu04nmfpy56sffn7c56tp9jzf9atnv9s4u6ev6

creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *squid
      - *squid-rig
      - *squid-top
      - *caddy-dmz
      - *caddy-internal
      - *timesquid-0
      - *ns1
      - *ns2
      - *mail
      - *i2p
      - *crowdsec
      - *otel
      - *torrent
      - *squidjelly
      - *squidcasts
      - *minesquid-velocity
      - *minesquid
      - *unimatrix
      - *umami
      - *uptime
      - *squidsurvey
      - *gigglesquidtech
      - *thatferretblog
      - *thatferretshop
      - *cfwrs
      - *boinc-tentacle0
      - *searxng
      - *atuin
      - *warrior-archiveteam
      - *attic
      - *ncps
      - *vaultwarden
      - *netbox
