# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &squid age1dwp8gxep67hf2mux2e54qqel6cs7ndvp008vsdv5t984s68reu0sxkm04q

  - &squid-rig age1qvktpvzde3rfnjnt3y9s9fvt9m23cgzqmp5qhgtrwgwqp70m7ewqnkkup4
  - &squid-top age1mfe5l2x5prlvdxzy9vnfau7grl8xyapnzud9qqk6hx9uagj0sppsjlt0v0

  - &caddy age1hp8fnxf6dvd7rznhx37aau5yr40jvvzsz8xc82t8cdwdzsxx5atsgshala

  - &timesquid-0 age1xjudtumpl945cdewuukwlzm9l0xvcaev0ae97ucf7ggkvlhuquusj0n7cu

  - &ns-root age17fhjh5pvuph39spz8d3x445gajfw4h0cq3t2mj29l83y6tlazg9sqpkdvu
  - &ns1 age1ukvapr6llvuw6yddkr3srcnpkhj4r0hyhup0yj0ft80lmutwcdeqyq7j7f
    
  - &cephalonetes-server-1 age13yyayp56jjnjk2qsk3380jcu82dftwgpsteyr7x0kaghzvdxvsrq2hwl4q
  - &cephalonetes-server-2 age10nt49epgyctvee5lsq506cyczaykn58nlu3r3cpmjkrhjfje2ses7hgp85
  - &cephalonetes-server-3 age1qqvgcagxzt5q02tweg7qwz3x40p0h3jguwqphfhpfkv0pxmg3y7qkwp0q5
  - &cephalonetes-agent-1 age19l9at5nxnrf504vac3wd6hgdacl7m8cyvd7aqmq43tt48hz5k9tsjnfs9s
  - &cephalonetes-agent-2 age1wzu8fm2zuwxu8sa6ldjxgtjalfvgy9wswpy79vwaw23ly9frl36smf4sme
  - &cephalonetes-agent-3 age195ehdg77mrxpce8ma5fxn9tzrdka5zcrqvhcd6jg9ducq703ws0qs0fjxw

creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *squid
      - *squid-rig
      - *squid-top
      - *caddy
      - *timesquid-0
      - *ns-root
      - *ns1
      - *cephalonetes-server-1
      - *cephalonetes-server-2
      - *cephalonetes-server-3
      - *cephalonetes-agent-1
      - *cephalonetes-agent-2
      - *cephalonetes-agent-3
