# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &squid age1dwp8gxep67hf2mux2e54qqel6cs7ndvp008vsdv5t984s68reu0sxkm04q

  - &squid-rig age1qvktpvzde3rfnjnt3y9s9fvt9m23cgzqmp5qhgtrwgwqp70m7ewqnkkup4
  - &squid-top age1mfe5l2x5prlvdxzy9vnfau7grl8xyapnzud9qqk6hx9uagj0sppsjlt0v0

  - &caddy-dmz age1uuuqrhvn5kx4qd92xjv0qmj85ve2c53g85gypvzku77m67qm2pasflluqq
  - &caddy-internal age1k8wmvwravcdk5gsh2k6rhe003ardaup476nn8mafdmzrs30f6vasf2mgae

  - &timesquid-0 age1m6qkmvryf4fmmus2nrmrauphlsqtt6q8flzd2wyn30xgplvse9msk0tarv

  - &ns1 age1j7cl3wapeduevrz89r30ejktt4l0u79d4qecjuadvfxthmk2pdds4cvhpp
  - &ns2 age1t423w78ykm3c8yqe2jdw5t87pckev278tfvwgtshcetu2yve7e7sv5edv9

  - &mail age17pmfukx50ak5rfmtzekk9rm6z4hj7n43kmzcrgqy37c97m3y0u3q23fwvc

  - &i2p age1naucvcsg7p4hjp3fz0y0dh2c6c6ue5wph2paza26r8qzryl87dzq48r9ck

  - &crowdsec age1mr64tx3uurhdsca75u9fd9gtn0jr8rw578ejljw0q0c9zvu0eaas9l7vs0
  - &otel age1nwqz2a2rgvaqcz7lmnjd5ryxyecv0h5h46lx88ma3gx2h4f28ahqe8rjrf

  - &torrent age1zswh4xxkyax7m527lx4slu45nfav57rs7frv2l3wuhhcvfm83yrqp27ezm
  - &squidjelly age14w9jvwngg85ph6e7yal3t5xmpg20s393vndgmznzl2vdfqgcsv0qy2huzn
  - &squidcasts age1tvesv74czg5uw9cce9gvzmda9xfdlk9g0ua6d37jkqyla6ayxv2sxfr5g4

  - &minesquid-velocity age1w2ehy9jxjktra2gfm4yz2ah92z3eedfjh9z4hd32293r2pzas5tst9995h
  - &minesquid age1r04g2t3ttcafjghfurvshqrtdepev2qt062lzvevk9txnzw2f4yswdunew

  - &unimatrix age1xp8y9snexane7duz53h8xx0vwxy8a6mhdh2rn5edrjuts5fegsgqxl7ecd

  - &umami age1cth8tyun4jrm4syafscm8hjp0crdkzyujj9f94afzrs42txy0dss85znkn

  - &gigglesquidtech age1735wpngc823k4trcp0ayzfnreqntvez8uymz048sv4wy59h0k9jq3r6pmj
  - &thatferretblog age1vghjsjt0rnqw8spwdgqesaqjs8kg725wkvvmhua94j3uaryg0c9snj6u67
  - &thatferretshop age16uf9ff3933s2uyxu74cgm34090k9pr8z4g0n33nlzrt76ha3wfcq0aayzp
  - &cfwrs age1as0xm26nvwdvxqyw6wg0je8zhwvjt8szqedzm88svwaw7uea6dds7q8n3z

  - &boinc-tentacle0 age13mk5pue6mlr3rjkrppxafcc2wz8wsygdhnt4jx335wxwaph5yads057hej

  - &searxng age1uzsyvn7arkk5xs6tagcn3leu2zn52equl3f66yhq2shdx3pzj3msgr77lx

  - &atuin age13mwtjzqadx0ylnft42j6qep96aktfkp9zndt2ekg6cjywzrske8qtcfh5j

  - &warrior-archiveteam age15dnpa7pl8u7660dpl5n8h69tdqx3jptv5wmrp337qn8qz7akcy8s4xrepd

creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *squid
      - *squid-rig
      - *squid-top
      - *caddy-dmz
      - *caddy-internal
      - *timesquid-0
      - *ns1
      - *ns2
      - *mail
      - *i2p
      - *crowdsec
      - *otel
      - *torrent
      - *squidjelly
      - *squidcasts
      - *minesquid-velocity
      - *minesquid
      - *unimatrix
      - *umami
      - *gigglesquidtech
      - *thatferretblog
      - *thatferretshop
      - *cfwrs
      - *boinc-tentacle0
      - *searxng
      - *atuin
      - *warrior-archiveteam
