# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &squid age1dwp8gxep67hf2mux2e54qqel6cs7ndvp008vsdv5t984s68reu0sxkm04q

  - &squid-rig age1v47gzxuhfxs389gmyecaz7ng6xzzm4x5l9a53cqdeh4kv3hj0axqr25unm
  - &squid-top age1mfe5l2x5prlvdxzy9vnfau7grl8xyapnzud9qqk6hx9uagj0sppsjlt0v0

  - &caddy age1hp8fnxf6dvd7rznhx37aau5yr40jvvzsz8xc82t8cdwdzsxx5atsgshala

  - &timesquid-0 age1xjudtumpl945cdewuukwlzm9l0xvcaev0ae97ucf7ggkvlhuquusj0n7cu

  - &ns-root age17fhjh5pvuph39spz8d3x445gajfw4h0cq3t2mj29l83y6tlazg9sqpkdvu
  - &ns1 age1ukvapr6llvuw6yddkr3srcnpkhj4r0hyhup0yj0ft80lmutwcdeqyq7j7f
    
  - &cephalonetes-server-1 age1rvupqt5eznce3g4xl2spzc3dr4k3csqrzxjlkmuzuhkzrzgdzvzqr7vl5p
  - &cephalonetes-server-2 age1heenc7wtx0mtgpwch6ky8e2n8dr9tppfuvjd49ltlmtuaeznqc2q2qjhp0
  - &cephalonetes-server-3 age18epjr653t6nku9w9nu8udz74eyzl54qmlgyagfrpkyttqep5kg0sdyjn7a
  - &cephalonetes-longhorn-1 age1yumyyq4ujhtq05vhzz86tpv3em75ujrq6y80ns2g80ctyftqvppst8fdkl
  - &cephalonetes-longhorn-2 age1j8z0xlzl3cnd03rfr2e23nfmme7le0t6u8zce5qgsfa8kx80pfvsdwukyu
  - &cephalonetes-longhorn-3 age1dgew0y4f072wjudenzqvrp30atvhgew5k2gz3v9juck4vl77cqvsuujleh
  - &cephalonetes-agent-1 age10qplnnu39na0zy57t4ku95lluumfa8wthudskuz4u6y6ulm28p5sz87h6a
  - &cephalonetes-agent-2 age1qujaahmj7zpels8eyk82qfcxle68h7jcuz882vnhfmnzhpgjvqxsjl9d25
  - &cephalonetes-agent-3 age1zkvmw3a466lnuwe7fgcrays035wcys3x88k3rmm929lvrh6q0g2s39lyre

creation_rules:
  - path_regex: sops/[^/]+\.yaml$
    key_groups:
    - age:
      - *squid
      - *squid-rig
      - *squid-top
      - *caddy
      - *timesquid-0
      - *ns-root
      - *ns1
      - *cephalonetes-server-1
      - *cephalonetes-server-2
      - *cephalonetes-server-3
      - *cephalonetes-longhorn-1
      - *cephalonetes-longhorn-2
      - *cephalonetes-longhorn-3
      - *cephalonetes-agent-1
      - *cephalonetes-agent-2
      - *cephalonetes-agent-3
