# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            tolerations:
              - effect: NoExecute
                key: CriticalAddonsOnly
                operator: Exists
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=flux"
