apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: caddy-ingress-controller
  namespace: caddy-system
spec:
  interval: 1m0s
  url: https://caddyserver.github.io/ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: caddy-ingress-controller
  namespace: caddy-system
spec:
  chart:
    spec:
      chart: caddy-ingress-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: caddy-ingress-controller
      version: 1.1.0
  loadBalancer:
    annotations:
      kube-vip.io/loadbalancerIPs: 10.10.5.10
  interval: 1m0s
