apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
      version: 1.14.0
  driftDetection:
    mode: enabled
  interval: 10m0s
  values:
    storage:
      useAllNodes: true
      useAllDevices: true
      deviceFilter: sda
      config:
        databaseSizeMB: "1024"
    cephClusterSpec:
      mgr:
        modules:
          - name: rook
            enabled: true
      dashboard:
        ssl: false
---
# Because: https://github.com/caddyserver/ingress/issues/211
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-dashboard
  namespace: rook-ceph
  annotations: 
    caddy.ingress.kubernetes.io/disable-ssl-redirect: "true"
    kubernetes.io/ingress.class: caddy
    meta.helm.sh/release-name: rook-cluste
    rmeta.helm.sh/release-namespace: rook-ceph
spec:
  rules:
  - host: rook.cephalonetes.lan.gigglesquid.tech
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 7000
        path: /
        pathType: Prefix
