apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-cluster
  namespace: rook-ceph
spec:
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
      version: 1.14.0
  driftDetection:
    mode: enabled
  interval: 10m0s
  values:
    storage:
      useAllNodes: true
      useAllDevices: true
      deviceFilter: sda
      config:
        databaseSizeMB: "1024"
    dashboard:
      ssl: false
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: caddy
          caddy.ingress.kubernetes.io/disable-ssl-redirect: "true"
        host:
          name: rook.cephalonetes.lan.gigglesquid.tech
