apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.6.1
  interval: 1m0s
  values:
    defaultSettings:
      taintToleration: "LonghornOnly=true:NoExecute"
    longhornDriver:
      tolerations:
      - key: "LonghornOnly"
        operator: "Exists"
        effect: "NoExecute"
    longhornManager:
      tolerations:
      - key: "LonghornOnly"
        operator: "Exists"
        effect: "NoExecute"
    longhornUI:
      tolerations:
      - key: "LonghornOnly"
        operator: "Exists"
        effect: "NoExecute"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: caddy
    caddy.ingress.kubernetes.io/disable-ssl-redirect: "true"
spec:
  rules:
  - host: longhorn.cephalonetes.lan.gigglesquid.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
