apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      interval: 10m
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.9.6
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 6000Mi
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44 # video
              - 105 # jellyfin
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config
    persistence:
          transcode:
            type: emptyDir
            globalMounts:
              - path: /transcode
          cache:
            type: emptyDir
            globalMounts:
              - path: /cache
          media:
            type: nfs
            server: cephalonas.lan.gigglesquid.tech
            path: /mnt/main/media/squidjelly
            globalMounts:
              - path: /media
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8096
    ingress:
      main:
        enabled: true
        annotations: 
          caddy.ingress.kubernetes.io/disable-ssl-redirect: "true"
          kubernetes.io/ingress.class: caddy
        hosts:
        - host: squidjelly.cephalonetes.lan.gigglesquid.tech
          paths:
          - path: /
            pathType: Prefix
            service:
              name: jellyfin
              port: *port
