apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: caddy-ingress-controller
  namespace: caddy-system
spec:
  chart:
    spec:
      chart: caddy-ingress-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: caddy-ingress-controller-charts
      version: 1.1.0
  driftDetection:
    mode: enabled
  values:
    loadBalancer:
      annotations:
        kube-vip.io/loadbalancerIPs: 10.10.4.10
    ingressController:
      config:
        acmeCA: https://acme-staging-v02.api.letsencrypt.org/directory
        email: jack.connors@protonmail.com
  interval: 10m0s
