# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e480ed69-1f2e-4a7b-b1bb-3599aa5da2f7";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-93833359-9121-48e4-88d5-3c37eca63b20".device = "/dev/disk/by-uuid/93833359-9121-48e4-88d5-3c37eca63b20";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1BBB-A652";
    fsType = "vfat";
  };

  fileSystems."/mnt/backups" = {
    device = "/dev/disk/by-uuid/95a47dae-280d-4fd1-a6ff-309db8ed338b";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8c8c3fe4-b5df-4d60-b141-5d5ad6b6a32a".device = "/dev/disk/by-uuid/8c8c3fe4-b5df-4d60-b141-5d5ad6b6a32a";

  fileSystems."/mnt/steam" = {
    device = "/dev/disk/by-uuid/e60c1aa4-1c16-49cd-b349-eb433f368145";
    fsType = "ext4";
  };

  fileSystems."/mnt/cephalonas/backups/squid-rig" = {
    device = "cephalonas.lan.gigglesquid.tech:/mnt/Main/Backups/Squid-Rig";
    fsType = "nfs";
    noCheck = true;
  };

  fileSystems."/mnt/cephalonas/media" = {
    device = "cephalonas.lan.gigglesquid.tech:/mnt/Main/Media";
    fsType = "nfs";
    noCheck = true;
  };

  fileSystems."/mnt/cephalonas/torrents" = {
    device = "cephalonas.lan.gigglesquid.tech:/mnt/Torrents/qbittorrent";
    fsType = "nfs";
    noCheck = true;
  };

  swapDevices = [{device = "/dev/disk/by-uuid/25fa2d30-83e4-4b5a-b8c2-07db3fc153f6";}];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.swraid.enable = true;
}
